const { resolveModel } = require('./model-select');

const GEMINI_API_KEY = process.env.GOOGLE_GENAI_API_KEY || process.env.GEMINI_API_KEY;

// Modellwahl laeuft durch die zentrale Politik (model-select.js) und wird pro
// Request aufgeloest — vorher war der Endpoint zur Modul-Ladezeit auf den rohen
// GEMINI_TEXT_MODEL-ENV-Pin gebacken und umging die Modellpolitik komplett
// (einziger Prod-Aufrufer: services/ebay-auto-fix.js Aspect-Generierung).
function resolveTextEndpoint() {
  const model = resolveModel(null, 'GEMINI_TEXT_MODEL', null);
  return `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent`;
}

function ensureGeminiApiKey() {
  if (!GEMINI_API_KEY) {
    throw new Error('GEMINI_API_KEY or GOOGLE_GENAI_API_KEY must be configured for text generation.');
  }
}

async function generateText(prompt, options = {}) {
  ensureGeminiApiKey();
  if (!prompt || !prompt.toString().trim()) {
    throw new Error('Prompt is required for Gemini text generation.');
  }

  const body = {
        contents: [
            {
                role: 'user',
        parts: [{ text: prompt.toString() }],
            },
        ],
        generationConfig: {
      temperature: typeof options.temperature === 'number' ? options.temperature : 0.7,
      maxOutputTokens: typeof options.maxOutputTokens === 'number' ? options.maxOutputTokens : 1024,
      topP: typeof options.topP === 'number' ? options.topP : 0.8,
      topK: typeof options.topK === 'number' ? options.topK : 40,
        },
    };

  const response = await fetch(`${resolveTextEndpoint()}?key=${encodeURIComponent(GEMINI_API_KEY)}`, {
        method: 'POST',
        headers: {
      'Content-Type': 'application/json',
        },
    body: JSON.stringify(body),
    });

    if (!response.ok) {
        const errorText = await response.text();
    let reason = errorText;
    try {
      const parsed = JSON.parse(errorText);
      reason = parsed.error?.message || JSON.stringify(parsed.error) || reason;
    } catch (err) {
      // ignore JSON parse issues, fall back to raw text
    }
    throw new Error(`Gemini API failed (${response.status}): ${reason}`);
    }

    const data = await response.json();
  const parts = data.candidates?.[0]?.content?.parts || [];
  const text = parts
    .map((part) => part?.text)
    .filter(Boolean)
    .join('\n')
    .trim();

    if (!text) {
        throw new Error('No text generated by Gemini');
    }

    return text;
}

module.exports = {
    generateText,
};
